### ISSUE TITLE
Key Bug

### ISSUE THREAD

**Issue by ppzh0** [takamimusubinomikoto/Unicode-Zawgyi-Online-Keyboard#1]
When I pressed on `Shift` and it starts to repeat again and again
<hr>

**This is before pressing Shift**

![image](https://user-images.githubusercontent.com/103206741/181924561-b2384221-6f2e-4d67-a5ea-7c704491ea67.png)

<hr>

**This is after pressing Shift**

![image](https://user-images.githubusercontent.com/103206741/181924676-97106780-65df-4593-99a8-bd67addeef56.png)

*Not holding Shift key*

**Comment by zayarlyn** [comment]
Hello!
Please can you specify the following:
- what device (mobile or desktop browser)
- how did you toggle (from the keyboard or manually clicking the up-arrow icon)
- when does the bug occur (does the green color persist after clicking the shift key from the physical keyboard or does it behave differently between clicking the physical key and the icon on the page or not persisting at all)

**Comment by tester-9e** [comment]
It occurs in Edge, FireFox and especially chrome on desktop.
When I use physical keyboard for Shift, it starts to repeat again and again.

**Comment by ppzh0** [comment]
It occurs in Edge, FireFox and especially chrome on desktop.
When I use physical keyboard for Shift, it starts to repeat again and again [If I long pressed on Shift], then stuck with green color _sometimes_. If I clicked on up arrow key on virtual keyboard, it become green color and if I use physical keyboard after that it become white which is default

**Comment by zayarlyn** [comment]
Let me explain what I did with that key.
For the physical keyboard, it will only be active when the **shift** key is pressed. (For fast typing)
For clicking it manually(with mouse or touch), it behaves like a toggle. (It is not possible to click both **Shift** and other keys simultaneously)
If this is the behavior you are facing it is not a bug: it is a feature. 😁
